# Generated by Django 4.2 on 2026-02-23 10:25

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('round', models.IntegerField(choices=[(1, 'Round 1 - General Questions'), (2, 'Round 2 - Pass The Mic'), (3, 'Round 3 - Buzzer Round'), (4, 'Round 4 - Rapid Fire')])),
                ('question', models.TextField()),
                ('answer', models.CharField(max_length=500)),
                ('options', models.JSONField(blank=True, null=True)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['round', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.CharField(choices=[('team_a', 'Tour Arcade Team A'), ('team_b', 'Tour Arcade Team B'), ('team_c', 'Tour Arcade Team C'), ('team_d', 'Tour Arcade Team D')], max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('score', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('answering', 'Answering'), ('locked', 'Locked'), ('timeout', 'Timeout'), ('buzzed', 'Buzzed')], default='waiting', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-score'],
            },
        ),
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('current_round', models.IntegerField(default=1)),
                ('current_question_index', models.IntegerField(default=0)),
                ('timer_seconds', models.IntegerField(default=0)),
                ('is_timer_running', models.BooleanField(default=False)),
                ('round_type', models.CharField(choices=[('general', 'General Questions'), ('pass-the-mic', 'Pass The Mic'), ('buzzer', 'Buzzer Round'), ('rapid-fire', 'Rapid Fire')], default='general', max_length=20)),
                ('buzzer_enabled', models.BooleanField(default=False)),
                ('buzzer_order', models.JSONField(default=list)),
                ('question_revealed', models.BooleanField(default=False)),
                ('game_started', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_sessions', to='quiz_api.team')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('answer_text', models.TextField()),
                ('is_correct', models.BooleanField(blank=True, null=True)),
                ('points_awarded', models.IntegerField(default=0)),
                ('time_taken', models.IntegerField(help_text='Seconds taken to answer')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='quiz_api.question')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz_api.gamesession')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz_api.team')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
